# Python CircleCI 2.0 configuration file
version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7

    working_directory: ~/repo

    steps:
      # Step 1: obtain repo from GitHub
      - checkout
      # Step 2: create virtual env and install dependencies
      - run:
          name: install dependencies
          command: |
            sudo apt install pipenv
            pipenv --three
            pipenv install -e
      # Step 3: run linter and tests
      - run:
          name: run tests
          command: |
            pipenv shell
            pytest -v --cov ./crawto
